In [823]:
import pandas as pd
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt


df = pd.read_csv('loan_approval_dataset.csv')
df.columns

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [824]:
le = LabelEncoder()

df[' education'] = le.fit_transform(df[' education'])
df[' self_employed'] = le.fit_transform(df[' self_employed'])
df[' loan_status'] = le.fit_transform(df[' loan_status'])
df.drop('loan_id', axis=1, inplace=True)

df.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1

In [825]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0    no_of_dependents          4269 non-null   int64
 1    education                 4269 non-null   int64
 2    self_employed             4269 non-null   int64
 3    income_annum              4269 non-null   int64
 4    loan_amount               4269 non-null   int64
 5    loan_term                 4269 non-null   int64
 6    cibil_score               4269 non-null   int64
 7    residential_assets_value  4269 non-null   int64
 8    commercial_assets_value   4269 non-null   int64
 9    luxury_assets_value       4269 non-null   int64
 10   bank_asset_value          4269 non-null   int64
 11   loan_status               4269 non-null   int64
dtypes: int64(12)
memory usage: 400.3 KB

In [826]:
df['Total assets'] = df[' residential_assets_value'] + df[' commercial_assets_value'] + df[' luxury_assets_value'] + df[' bank_asset_value']
df.rename(columns={'Total assets': 'Total Assets Value'}, inplace=True)
df['DTI'] = df[' loan_amount'] / df[' income_annum']
df['Income x Loan Term'] = df[' income_annum'] * df[' loan_term']
df['Loan to Asset Ratio'] = df[' loan_amount'] / df['Total Assets Value']
df['Total asset ratio x Income'] = df['Total Assets Value'] / df[' income_annum']
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,Total Assets Value,DTI,Income x Loan Term,Loan to Asset Ratio,Total asset ratio x Income
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0,50700000,3.114583,115200000,0.589744,5.281250
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1,17000000,2.975610,32800000,0.717647,4.146341
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1,57700000,3.263736,182000000,0.514731,6.340659
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1,52700000,3.743902,65600000,0.582543,6.426829
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1,55000000,2.469388,196000000,0.440000,5.612245

In [827]:
# import matplotlib.pyplot as plt
# import seaborn as sns
# import pandas as pd

# plt.figure(figsize=(10, 6))
# sns.set_palette("bright")
# sns.lineplot(data=df, x='Income x Loan Term', y=' loan_amount', marker='o')
# plt.xlabel("Income x Loan Term")
# plt.ylabel("Loan Amount")
# plt.title("Income x Loan Term vs Loan Amount")
# plt.show()

In [828]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0    no_of_dependents           4269 non-null   int64
 1    education                  4269 non-null   int64
 2    self_employed              4269 non-null   int64
 3    income_annum               4269 non-null   int64
 4    loan_amount                4269 non-null   int64
 5    loan_term                  4269 non-null   int64
 6    cibil_score                4269 non-null   int64
 7    residential_assets_value   4269 non-null   int64
 8    commercial_assets_value    4269 non-null   int64
 9    luxury_assets_value        4269 non-null   int64
 10   bank_asset_value           4269 non-null   int64
 11   loan_status                4269 non-null   int64
 12  Total Assets Value          4269 non-null   int64
 13  DTI                         4269 non-null   float64
 14  Income x Loan Term          4269 non-null   int64
 15  Loan to Asset Ratio         4269 non-null   float64
 16  Total asset ratio x Income  4269 non-null   float64
dtypes: float64(3), int64(14)
memory usage: 567.1 KB

#Scaling data

---

In [829]:
# # prompt: apply standard scaler to columns

# from sklearn.preprocessing import StandardScaler

# # Select numerical columns for scaling
# numerical_cols = [' loan_amount', 'Total Assets Value', 'Income x Loan Term', ' residential_assets_value', ' commercial_assets_value', ' luxury_assets_value', ' bank_asset_value',]

# # Create a StandardScaler object
# scaler = StandardScaler()

# # Fit and transform the selected columns
# df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [830]:
# separate dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(labels=[' loan_status'], axis=1),
    df[' loan_status'],
    test_size=0.2,
    random_state=0)

In [831]:
# import seaborn as sns
# #Using Pearson Correlation
# plt.figure(figsize=(12,10))
# cor = X_train.corr()
# sns.heatmap(cor, annot=True, cmap=plt.cm.CMRmap_r)
# plt.show()

#**Information Gain And Mutual Information**


---

In [832]:
# from sklearn.feature_selection import mutual_info_classif
# # determine the mutual information
# mutual_info = mutual_info_classif(X_train, y_train)
# print(mutual_info)
# mutual_info = pd.Series(mutual_info)
# mutual_info.index = X_train.columns
# mutual_info.sort_values(ascending=False)
# #let's plot the ordered mutual_info values per feature
# mutual_info.sort_values(ascending=False).plot.bar(figsize=(20, 8))

# from sklearn.feature_selection import SelectKBest
# sel_five_cols = SelectKBest(mutual_info_classif, k=5)
# sel_five_cols.fit(X_train, y_train)
# X_train.columns[sel_five_cols.get_support()]

# #Effect

# # X_train = X_train[X_train.columns[sel_five_cols.get_support()]]
# # X_test = X_test[X_test.columns[sel_five_cols.get_support()]]

#**Correlation Method**

---

In [833]:
# # with the following function we can select highly correlated features
# # it will remove the first feature that is correlated with anything other feature

# def correlation(dataset, threshold):
#     col_corr = set()  # Set of all the names of correlated columns
#     corr_matrix = dataset.corr()
#     for i in range(len(corr_matrix.columns)):
#         for j in range(i):
#             if corr_matrix.iloc[i, j] > threshold: # we are interested in absolute coeff value
#                 colname = corr_matrix.columns[i]  # getting the name of column
#                 col_corr.add(colname)
#     return col_corr

# corr_features = correlation(X_train, 0.7)

# print(len(set(corr_features)))

# print(corr_features)

# #Effect
# X_train.drop(corr_features,axis=1, inplace=True)
# X_test.drop(corr_features,axis=1, inplace=True)
# X_train.columns

#**Variance Threshold**

---

In [834]:
# from sklearn.feature_selection import VarianceThreshold

# var_thres=VarianceThreshold(threshold=0.7)
# var_thres.fit(X_train)
# print(var_thres.get_support())
# sum(var_thres.get_support())
# selected_features = X_train.columns[var_thres.get_support()]
# print(selected_features)

# constant_columns = [column for column in X_train.columns
#                     if column not in X_train.columns[var_thres.get_support()]]

# print("Number of columns to be eliminated: ", len(constant_columns))
# for column in constant_columns:
#     print(column)

# #Effect
# X_train.drop(constant_columns,axis=1, inplace=True)
# X_test.drop(constant_columns,axis=1, inplace=True)
# X_train.columns

#Wrapper Methods

---
- Forward Selection

In [835]:
# from mlxtend.feature_selection import SequentialFeatureSelector as SFS
# from sklearn.tree import DecisionTreeClassifier

# # Define features and target variable
# X = df.drop(columns=[' loan_status'])
# y = df[' loan_status']

# # Initialize the model
# model = DecisionTreeClassifier(random_state=0)

# # Perform forward selection
# sfs = SFS(model,
#           k_features=4,  # Select top 10 features
#           forward=True,
#           floating=False,
#           scoring='accuracy',
#           cv=5)


# sfs = sfs.fit(X, y)

# print(pd.DataFrame.from_dict(sfs.get_metric_dict()).T)
# # Get selected features
# selected_features = list(sfs.k_feature_names_)

# print("Selected features (Decision Tree):")
# print(selected_features)
# # prompt: Select the selected features for X_train and test

# X_train = X_train[selected_features]
# X_test = X_test[selected_features]

# print(X_train)

#Embedded Methods

---
- Lasso

In [836]:
# from sklearn.linear_model import Lasso

# lasso = Lasso(alpha=0.1)
# lasso.fit(X_train, y_train)

# selected_features = X_train.columns[lasso.coef_ != 0]
# print("Selected features:", selected_features)

# #Effect
# X_train = X_train[selected_features]
# X_test = X_test[selected_features]

Selected features: Index([' income_annum', ' loan_amount', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', 'Total Assets Value',
       'Income x Loan Term'],
      dtype='object')

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.415e+01, tolerance: 8.007e-02
  model = cd_fast.enet_coordinate_descent(

In [837]:
# prompt: Employ Logistic regression, Random forest and decision trees
from sklearn.linear_model import LogisticRegression

# Logistic Regression
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)

print("Logistic Regression:")
classification_report(y_test, lr_pred)
"Accuracy:", accuracy_score(y_test, lr_pred)

Logistic Regression:

('Accuracy:', 0.6065573770491803)

In [838]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix # import confusion_matrix

# Random Forest
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

print("\nRandom Forest:")
print(classification_report(y_test, rf_pred))
print("Accuracy:", accuracy_score(y_test, rf_pred))
tn, fp, fn, tp = confusion_matrix(y_test, rf_pred).ravel()

# Calculate specificity
specificity = tn / (tn + fp)

print(f"Confusion Matrix:\n{confusion_matrix(y_test, rf_pred)}")
print(f"Specificity: {specificity:.4f}")

Random Forest:
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       523
           1       0.97      0.99      0.98       331

    accuracy                           0.98       854
   macro avg       0.98      0.99      0.98       854
weighted avg       0.98      0.98      0.98       854

Accuracy: 0.9847775175644028
Confusion Matrix:
[[513  10]
 [  3 328]]
Specificity: 0.9809

In [839]:
# Decision Tree
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)

print("\nDecision Tree:")
print(classification_report(y_test, dt_pred))
print("Accuracy:", accuracy_score(y_test, dt_pred))

Decision Tree:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       523
           1       0.95      0.95      0.95       331

    accuracy                           0.96       854
   macro avg       0.96      0.96      0.96       854
weighted avg       0.96      0.96      0.96       854

Accuracy: 0.9637002341920374

In [798]:
from sklearn.model_selection import cross_val_score

# Perform 5-fold cross-validation
cv_scores = cross_val_score(rf_model, X_train, y_train, cv=5)

print(f"Cross-Validation Scores: {cv_scores}")
print(f"Mean CV Score: {cv_scores.mean()}")
print(f"Standard Deviation of CV Score: {cv_scores.std()}")

Cross-Validation Scores: [0.97657394 0.9795022  0.98389458 0.96632504 0.98389458]
Mean CV Score: 0.9780380673499268
Standard Deviation of CV Score: 0.006481974706055246