In [34]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier
#Import decision tree
from sklearn.tree import DecisionTreeClassifier

In [35]:
df = pd.read_csv('loan_approval_dataset.csv')
df.drop('loan_id', axis=1, inplace=True)
df.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0    no_of_dependents          4269 non-null   int64
 1    education                 4269 non-null   object
 2    self_employed             4269 non-null   object
 3    income_annum              4269 non-null   int64
 4    loan_amount               4269 non-null   int64
 5    loan_term                 4269 non-null   int64
 6    cibil_score               4269 non-null   int64
 7    residential_assets_value  4269 non-null   int64
 8    commercial_assets_value   4269 non-null   int64
 9    luxury_assets_value       4269 non-null   int64
 10   bank_asset_value          4269 non-null   int64
 11   loan_status               4269 non-null   object
dtypes: int64(9), object(3)
memory usage: 400.3+ KB

In [37]:

le = LabelEncoder()

df[' education'] = le.fit_transform(df[' education'])
df[' self_employed'] = le.fit_transform(df[' self_employed'])
df[' loan_status'] = le.fit_transform(df[' loan_status'])

df.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1

In [38]:
# from sklearn.tree import DecisionTreeClassifier

# # Define features and target variable
# X = df.drop(columns=[' loan_status'])
# y = df[' loan_status']

# # Initialize Decision Tree classifier
# model = DecisionTreeClassifier(random_state=0)

# # Fit the model
# model.fit(X, y)

# # Get feature importances
# feature_importances = model.feature_importances_

# # Create DataFrame to store feature importances
# feature_importance_df = pd.DataFrame({
#     'Feature': X.columns,
#     'Importance': feature_importances
# })

# # Sort features by importance (descending order)
# feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# # Perform backward elimination based on feature importances
# def backward_elimination_decision_tree(X, feature_importance_df, num_features=10):
#     selected_features = feature_importance_df.head(num_features)['Feature'].tolist()
#     return selected_features

# selected_features_dt = backward_elimination_decision_tree(X, feature_importance_df)

# print("Selected features after backward elimination (Decision Tree):")
# print(selected_features_dt)



from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Define features and target variable
X = df.drop(columns=[' loan_status'])
y = df[' loan_status']

# Initialize Random Forest classifier
model_rf = RandomForestClassifier(random_state=0)

# Fit the model
model_rf.fit(X, y)

# Get feature importances
feature_importances_rf = model_rf.feature_importances_

# Create DataFrame to store feature importances
feature_importance_df_rf = pd.DataFrame({
    'Feature': X.columns,
    'Importance': feature_importances_rf
})

# Sort features by importance (descending order)
feature_importance_df_rf = feature_importance_df_rf.sort_values(by='Importance', ascending=False)

# Perform backward elimination based on feature importances
def backward_elimination_random_forest(X, feature_importance_df_rf, num_features=10):
    selected_features_rf = feature_importance_df_rf.head(num_features)['Feature'].tolist()
    return selected_features_rf

selected_features_rf = backward_elimination_random_forest(X, feature_importance_df_rf)

print("Selected features after backward elimination (Random Forest):")
print(selected_features_rf)

Selected features after backward elimination (Random Forest):
[' cibil_score', ' loan_term', ' loan_amount', ' luxury_assets_value', ' income_annum', ' residential_assets_value', ' commercial_assets_value', ' bank_asset_value', ' no_of_dependents', ' self_employed']

In [39]:
df = df[selected_features_dt]
df.head(5)
X = df
X

,cibil_score,loan_term,loan_amount,income_annum,luxury_assets_value,commercial_assets_value,no_of_dependents,residential_assets_value,bank_asset_value,education
0,778,12,29900000,9600000,22700000,17600000,2,2400000,8000000,0
1,417,8,12200000,4100000,8800000,2200000,0,2700000,3300000,1
2,506,20,29700000,9100000,33300000,4500000,3,7100000,12800000,0
3,467,8,30700000,8200000,23300000,3300000,3,18200000,7900000,0
4,382,20,24200000,9800000,29400000,8200000,5,12400000,5000000,1
...,...,...,...,...,...,...,...,...,...,...
4264,317,12,2300000,1000000,3300000,500000,5,2800000,800000,0
4265,559,20,11300000,3300000,11000000,2900000,0,4200000,1900000,1
4266,457,18,23900000,6500000,18100000,12400000,2,1200000,7300000,1
4267,780,8,12800000,4100000,14100000,700000,1,8200000,5800000,1
4268,607,10,29700000,9200000,35700000,11800000,1,17800000,12000000,0

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score

# Assuming X and y are defined as your features and target variable
# X should contain the selected features based on your feature selection process

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Initialize Decision Tree Classifier
decision_tree = DecisionTreeClassifier(random_state=0)

# Fit the model on the training data
decision_tree.fit(X_train, y_train)

# Predictions
y_pred = decision_tree.predict(X_test)

# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       775
           1       0.97      0.96      0.97       506

    accuracy                           0.97      1281
   macro avg       0.97      0.97      0.97      1281
weighted avg       0.97      0.97      0.97      1281

Accuracy: 0.9734582357533177

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
randomForest = RandomForestClassifier(n_estimators=100, random_state=0)
randomForest.fit(X_train, y_train)
y_pred = randomForest.predict(X_test)
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       775
           1       0.99      0.97      0.98       506

    accuracy                           0.98      1281
   macro avg       0.98      0.98      0.98      1281
weighted avg       0.98      0.98      0.98      1281

Accuracy: 0.9820452771272443