#**Forward Selection**
---

In [42]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

In [43]:
df = pd.read_csv('loan_approval_dataset.csv')
df.drop('loan_id', axis=1, inplace=True)
df.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [44]:

le = LabelEncoder()

df[' education'] = le.fit_transform(df[' education'])
df[' self_employed'] = le.fit_transform(df[' self_employed'])
df[' loan_status'] = le.fit_transform(df[' loan_status'])

df.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1

In [49]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.tree import DecisionTreeClassifier

# Define features and target variable
X = df.drop(columns=[' loan_status'])
y = df[' loan_status']

# Initialize the model
model = DecisionTreeClassifier(random_state=0)

# Perform forward selection
sfs = SFS(model,
          k_features=6,  # Select top 10 features
          forward=True,
          floating=False,
          scoring='accuracy',
          cv=5)


sfs = sfs.fit(X, y)

pd.DataFrame.from_dict(sfs.get_metric_dict()).T

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(6,)","[0.949648711943794, 0.936768149882904, 0.94613...",0.944484,"( cibil_score,)",0.005433,0.004227,0.002114
2,"(5, 6)","[0.9578454332552693, 0.9484777517564403, 0.953...",0.950808,"( loan_term, cibil_score)",0.006522,0.005075,0.002537
3,"(2, 5, 6)","[0.9578454332552693, 0.9519906323185011, 0.966...",0.955961,"( self_employed, loan_term, cibil_score)",0.007352,0.00572,0.00286
4,"(1, 2, 5, 6)","[0.955503512880562, 0.949648711943794, 0.96370...",0.955258,"( education, self_employed, loan_term, cibi...",0.006135,0.004773,0.002386
5,"(1, 2, 4, 5, 6)","[0.9613583138173302, 0.9508196721311475, 0.951...",0.955259,"( education, self_employed, loan_amount, lo...",0.004792,0.003729,0.001864
6,"(1, 2, 3, 4, 5, 6)","[0.9812646370023419, 0.9800936768149883, 0.983...",0.982198,"( education, self_employed, income_annum, l...",0.00175,0.001362,0.000681

In [50]:
# Get selected features
selected_features = list(sfs.k_feature_names_)

print("Selected features (Decision Tree):")
print(selected_features)

Selected features (Decision Tree):
[' education', ' self_employed', ' income_annum', ' loan_amount', ' loan_term', ' cibil_score']